development:
  adapter: mysql2
  database: empressa_shop
  username: root
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: empressa_production
  pool: 5
  username: empressa
  password:
